### ISSUE TITLE
Is this a build step? Couldn't it be runtime cache?

### ISSUE THREAD

**Issue by Ciantic** [redexp/react-separate-template#1]
Isn't JSX turned to some mishmash of JS, so can't we just turn the HTML to same sauce?

I mean it would allow this to be cached in runtime and be used e.g. directly in TypeScript, and other IDE's.

Basically it would look like this

```
function getTemplate(templateName) {
    // Return the JSX if in cache
    // Get the HTML
    // turn to JSX
    // cache the JSX
    // Return the JSX
}

var MenuExample = React.createClass({
    getInitialState: function() {
        return {focused: 0};
    },
    clicked: function(index) {
        this.setState({focused: index});
    },
    render: function() {
        var self = this;
        return getTemplate("Menu");
    }
});
```

**Comment by redexp** [comment]
Then it will be absolutely new tool. Also your `getTemplate` will generate static jsx code without loops and ifs and so on.
